[package]
name = "deepdarkness"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = { version = "3.1.12", features = ["derive"] }
rusqlite = "0.27.0"